heroku:
  action_cable:
    url: 'wss://ancient-shelf-98201.herokuapp.com/cable'
    allowed_request_origins: 
      url: 'https://ancient-shelf-98201.herokuapp.com'
      regex: "http://ancient-shelf-98201.herokuapp.com.*"